#line 2 "tokens.cpp"

#line 4 "tokens.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 103
#define YY_END_OF_BUFFER 104
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[320] =
    {   0,
        0,    0,  104,  102,  101,  101,   86,  102,   99,  100,
       92,   85,  102,   80,   81,   90,   89,   77,   88,   84,
       91,   42,   43,   78,   74,   93,   79,   94,   97,   98,
       40,   40,   82,   83,   95,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   75,   96,   76,   87,   73,    0,   51,    0,   59,
       76,   68,   60,    0,    0,   57,   65,   55,   66,   56,
       67,    0,   46,    1,    2,   58,   47,   42,    0,    0,
       42,   42,    0,   42,   43,   43,   43,   43,   83,   75,
       82,   64,   70,   72,   71,   63,   40,    0,    0,   61,

       40,   40,   40,   40,   40,   40,   40,   40,   40,   12,
       40,   40,   40,   40,   40,   40,   20,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   62,   69,
       44,   52,    0,   46,    2,   46,    0,   47,    0,   45,
       42,   42,   42,   42,    0,   41,   43,   43,   43,   43,
       54,   53,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   18,   40,   40,   23,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,    0,   46,    0,   46,
        0,   47,   45,   42,   49,   50,   41,    0,   41,   41,

       43,   40,   40,   40,    3,   40,    6,    7,   40,   40,
       40,   40,   14,   15,   40,   40,   19,   40,   24,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   37,   40,   40,    0,   46,   49,    0,   49,   50,
        0,   41,   41,    0,   48,   41,   41,    4,   40,   40,
        5,    9,   40,   40,   40,   40,   17,   40,   40,   40,
       40,   28,   40,   40,   40,   40,   40,   40,   35,   40,
       40,   39,    0,   49,   49,    0,    0,   50,   48,   41,
       40,   40,   40,   40,   13,   16,   22,   40,   40,   27,
       29,   30,   31,   32,   33,   40,   40,   40,    0,   49,

       40,   40,   40,   11,   40,   40,   34,   40,   40,    8,
       40,   10,   25,   26,   36,   38,   40,   21,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   29,   32,   33,
       34,   34,   35,   34,   34,   36,   34,   34,   34,   37,
       34,   34,   34,   34,   38,   34,   34,   39,   34,   34,
       40,   41,   42,   43,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   34,   54,   55,   56,   57,
       58,   59,   34,   60,   61,   62,   63,   64,   65,   66,
       67,   68,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[73] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    4,    1,    5,    5,
        5,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    5,    6,    6,    7,    7,    6,    6,    1,
        1,    1,    1,    6,    5,    5,    5,    5,    5,    5,
        6,    6,    6,    6,    7,    6,    6,    6,    7,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    1,    1,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[327] =
    {   0,
        0,    0,  550,  551,  551,  551,  524,   68,  551,  551,
       49,   67,  507,  551,  551,  522,   63,  551,   64,   62,
       73,   93,   84,  520,  551,   99,  520,   59,  551,  551,
        0,   89,  551,  551,  519,   65,  480,  482,   82,   29,
       51,   60,  483,   69,  482,  490,   84,  471,  480,  478,
      483,  551,   68,  551,  551,  551,  123,  551,    0,  551,
      551,  551,  551,  120,  524,  551,  551,  551,  551,  551,
      551,  516,  133,  551,    0,  551,  153,  158,  178,  195,
      105,  108,  515,  107,  203,  155,  121,  129,  551,  551,
      551,  506,  551,  551,  551,  505,    0,  130,  488,  551,

      470,  469,  470,  463,  475,  462,  477,  464,  470,  456,
      457,  454,  454,  457,  454,  451,    0,   96,  455,  168,
      453,  136,  172,  457,  450,  172,  173,  455,  551,  551,
      551,  551,  224,  551,    0,  227,  235,  551,  248,  251,
      117,  551,  471,  451,    0,  256,  143,  551,  469,  449,
      551,  551,  445,  446,  456,  442,  454,  449,  437,  139,
      451,  449,  445,  437,  443,  446,    0,  432,  436,    0,
      437,  434,  424,  422,  424,  426,  433,  419,  417,  417,
      429,  419,  423,  427,  428,  409,  259,  276,  269,  551,
      279,  284,  551,  551,  277,  285,  198,  309,  176,  253,

      551,  400,  395,  396,    0,  390,    0,    0,  381,  389,
      378,  384,    0,    0,  378,  375,    0,  378,    0,  373,
      373,  372,  368,  380,  370,  374,  378,  377,  374,  364,
      369,    0,  357,  367,  322,  326,  551,  334,  301,  551,
      347,  199,  551,  350,  353,  379,  357,    0,  352,  345,
        0,    0,  340,  333,  331,  318,    0,  316,  302,  305,
      300,    0,  304,  301,  302,  273,  281,  278,    0,  267,
      265,    0,  358,  363,  551,  371,  374,  381,  551,  551,
      261,  250,  239,  224,    0,    0,    0,  232,  228,    0,
        0,    0,    0,    0,    0,  224,  216,  209,  385,  390,

      191,  208,  201,    0,  182,  143,    0,  112,  101,    0,
       51,    0,    0,    0,    0,    0,   35,    0,  551,  445,
      452,  455,  462,  466,   92,  467
    } ;

static yyconst flex_int16_t yy_def[327] =
    {   0,
      319,    1,  319,  319,  319,  319,  319,  320,  319,  319,
      319,  319,  321,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      322,  322,  319,  319,  319,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  319,  319,  319,  319,  319,  320,  319,  320,  319,
      319,  319,  319,  321,  321,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  323,  319,  319,  319,  319,  319,
      319,  319,  324,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  322,  320,  321,  319,

      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  319,  319,
      319,  319,  319,  319,  323,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  325,  324,  319,  319,  319,  319,
      319,  319,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  319,  319,  319,  319,
      319,  319,  319,  319,  325,  326,  319,  319,  319,  319,

      319,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  319,  319,  319,  319,  326,  319,
      319,  319,  319,  319,  319,  319,  319,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  319,  319,  319,  319,  319,  319,  319,  319,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  319,  319,

      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,    0,  319,
      319,  319,  319,  319,  319,  319
    } ;

static yyconst flex_int16_t yy_nxt[624] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   31,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   33,
        4,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   31,   44,   31,   45,   31,   31,   31,   31,   46,
       47,   48,   49,   50,   51,   31,   31,   31,   52,   53,
       54,   55,   58,   60,   61,   62,   67,  109,   72,   69,
       73,   73,   73,   95,   96,   74,  110,   68,   70,   71,
       75,   63,  129,   98,  101,  102,  195,   76,   99,  103,

       77,  318,   85,   85,   85,  111,   90,  112,   59,   77,
      317,   78,   78,   79,  114,   80,  113,  115,  117,   86,
       91,   87,   92,   93,   80,  118,  106,   58,   81,  131,
       82,   83,   80,  107,   58,  121,  122,  130,   88,  108,
      141,   80,  142,  143,  142,  123,   87,   84,  124,  316,
      169,   73,   73,   73,  142,   82,  149,  170,   83,  315,
       65,  141,  144,   59,  133,  134,  148,  142,  134,  142,
       59,  136,  136,  136,   77,  150,   78,   78,   79,  142,
      148,  133,  134,  147,  137,  138,  176,  134,  138,   80,
      147,  148,  148,   81,   77,   82,   79,   79,   79,  209,

      210,  137,  138,  177,  314,  148,   80,  138,  139,   80,
      139,  246,   84,  140,  140,  140,  178,  148,  172,   77,
       82,   85,   85,   85,  182,  184,   80,  185,  173,  174,
      247,  179,  183,  242,   80,  243,  243,  187,   86,  187,
       87,  313,  188,  188,  188,  136,  136,  136,  191,  312,
      191,   80,  311,  192,  192,  192,  310,   88,  189,  190,
      243,  243,  190,  309,  308,   87,  140,  140,  140,  140,
      140,  140,  196,  307,  306,  189,  190,  188,  188,  188,
      305,  190,  235,  193,  235,  304,  193,  236,  236,  236,
      243,  197,  198,  199,  188,  188,  188,  192,  192,  192,

      193,  303,  192,  192,  192,  193,  302,  242,  134,  301,
      200,  134,  237,  238,  198,  243,  138,  298,  199,  138,
      240,  241,  244,  297,  244,  134,  296,  245,  245,  245,
      134,  237,  295,  138,  294,  238,  275,  276,  138,  240,
      236,  236,  236,  241,  236,  236,  236,  273,  293,  273,
      292,  291,  274,  274,  274,  275,  290,  289,  190,  276,
      277,  190,  277,  288,  287,  278,  278,  278,  245,  245,
      245,  245,  245,  245,  286,  190,  274,  274,  274,  285,
      190,  274,  274,  274,  299,  279,  299,  284,  279,  300,
      300,  300,  278,  278,  278,  237,  283,  282,  237,  278,

      278,  278,  279,  300,  300,  300,  281,  279,  300,  300,
      300,  280,  237,  240,  280,  272,  240,  237,  271,  270,
      269,  268,  275,  267,  266,  275,  265,  264,  263,  262,
      240,  261,  260,  259,  258,  240,  257,  256,  255,  275,
      254,  253,  252,  251,  275,   57,  250,   57,   57,   57,
       57,   57,   64,  249,  248,   64,   64,   64,   64,   97,
       97,   97,  135,  234,  135,  135,  135,  135,  135,  146,
      146,  239,  233,  239,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  208,  207,  206,  205,

      204,  203,  202,  201,  201,  194,  194,  186,  181,  180,
      175,  171,  168,  167,  166,  165,  164,  163,  162,  161,
      160,  159,  158,  157,  156,  155,  154,  153,   65,  152,
      151,  145,  132,   64,  128,  127,  126,  125,  120,  119,
      116,  105,  104,  100,   94,   89,   66,   65,   56,  319,
        3,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,

      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319
    } ;

static yyconst flex_int16_t yy_chk[624] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    8,   11,   11,   12,   17,   40,   20,   19,
       20,   20,   20,   28,   28,   21,   40,   17,   19,   19,
       21,   12,   53,   32,   36,   36,  325,   21,   32,   36,

       23,  317,   23,   23,   23,   41,   26,   41,    8,   22,
      311,   22,   22,   22,   42,   23,   41,   42,   44,   23,
       26,   23,   26,   26,   22,   44,   39,   57,   22,   64,
       22,   22,   23,   39,   98,   47,   47,   53,   23,   39,
       81,   22,   81,   82,   84,   47,   23,   22,   47,  309,
      118,   73,   73,   73,  141,   22,   87,  118,   22,  308,
       64,   84,   82,   57,   73,   73,   88,   81,   73,   84,
       98,   77,   77,   77,   78,   87,   78,   78,   78,  141,
      147,   73,   73,   88,   77,   77,  122,   73,   77,   78,
       86,   88,   86,   78,   79,   78,   79,   79,   79,  160,

      160,   77,   77,  122,  306,  147,   78,   77,   80,   79,
       80,  199,   78,   80,   80,   80,  123,   86,  120,   85,
       78,   85,   85,   85,  126,  127,   79,  127,  120,  120,
      199,  123,  126,  197,   85,  197,  242,  133,   85,  133,
       85,  305,  133,  133,  133,  136,  136,  136,  137,  303,
      137,   85,  302,  137,  137,  137,  301,   85,  136,  136,
      197,  242,  136,  298,  297,   85,  139,  139,  139,  140,
      140,  140,  146,  296,  289,  136,  136,  187,  187,  187,
      288,  136,  189,  140,  189,  284,  140,  189,  189,  189,
      200,  146,  146,  146,  188,  188,  188,  191,  191,  191,

      140,  283,  192,  192,  192,  140,  282,  200,  188,  281,
      146,  188,  195,  195,  146,  200,  192,  271,  146,  192,
      196,  196,  198,  270,  198,  188,  268,  198,  198,  198,
      188,  195,  267,  192,  266,  195,  239,  239,  192,  196,
      235,  235,  235,  196,  236,  236,  236,  238,  265,  238,
      264,  263,  238,  238,  238,  239,  261,  260,  236,  239,
      241,  236,  241,  259,  258,  241,  241,  241,  244,  244,
      244,  245,  245,  245,  256,  236,  273,  273,  273,  255,
      236,  274,  274,  274,  276,  245,  276,  254,  245,  276,
      276,  276,  277,  277,  277,  274,  253,  250,  274,  278,

      278,  278,  245,  299,  299,  299,  249,  245,  300,  300,
      300,  247,  274,  278,  246,  234,  278,  274,  233,  231,
      230,  229,  300,  228,  227,  300,  226,  225,  224,  223,
      278,  222,  221,  220,  218,  278,  216,  215,  212,  300,
      211,  210,  209,  206,  300,  320,  204,  320,  320,  320,
      320,  320,  321,  203,  202,  321,  321,  321,  321,  322,
      322,  322,  323,  186,  323,  323,  323,  323,  323,  324,
      324,  326,  185,  326,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  169,  168,
      166,  165,  164,  163,  162,  161,  159,  158,  157,  156,

      155,  154,  153,  150,  149,  144,  143,  128,  125,  124,
      121,  119,  116,  115,  114,  113,  112,  111,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,   99,   96,
       92,   83,   72,   65,   51,   50,   49,   48,   46,   45,
       43,   38,   37,   35,   27,   24,   16,   13,    7,    3,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,

      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "idjl.l"
#line 10 "idjl.l"
#include <stdio.h>
#include "y.tab.h"

void count(void);
#line 703 "tokens.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 16 "idjl.l"

#line 887 "tokens.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 320 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 551 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 17 "idjl.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 18 "idjl.l"
{ /* consume //-comment */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 21 "idjl.l"
{ count(); return(AUTO); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 22 "idjl.l"
{ count(); return(BOOL); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 23 "idjl.l"
{ count(); return(BREAK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 24 "idjl.l"
{ count(); return(CASE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 25 "idjl.l"
{ count(); return(CHAR); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 26 "idjl.l"
{ count(); return(COMPLEX); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 27 "idjl.l"
{ count(); return(CONST); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 28 "idjl.l"
{ count(); return(CONTINUE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 29 "idjl.l"
{ count(); return(DEFAULT); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 30 "idjl.l"
{ count(); return(DO); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 31 "idjl.l"
{ count(); return(DOUBLE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 32 "idjl.l"
{ count(); return(ELSE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 33 "idjl.l"
{ count(); return(ENUM); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 34 "idjl.l"
{ count(); return(EXTERN); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 35 "idjl.l"
{ count(); return(FLOAT); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 36 "idjl.l"
{ count(); return(FOR); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 37 "idjl.l"
{ count(); return(GOTO); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 38 "idjl.l"
{ count(); return(IF); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 39 "idjl.l"
{ count(); return(IMAGINARY); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 40 "idjl.l"
{ count(); return(INLINE); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 41 "idjl.l"
{ count(); return(INT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 42 "idjl.l"
{ count(); return(LONG); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 43 "idjl.l"
{ count(); return(REGISTER); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 44 "idjl.l"
{ count(); return(RESTRICT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 45 "idjl.l"
{ count(); return(RETURN); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 46 "idjl.l"
{ count(); return(SHORT); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 47 "idjl.l"
{ count(); return(SIGNED); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 48 "idjl.l"
{ count(); return(SIZEOF); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 49 "idjl.l"
{ count(); return(STATIC); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 50 "idjl.l"
{ count(); return(STRUCT); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 51 "idjl.l"
{ count(); return(SWITCH); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 52 "idjl.l"
{ count(); return(TYPEDEF); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 53 "idjl.l"
{ count(); return(UNION); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 54 "idjl.l"
{ count(); return(UNSIGNED); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 55 "idjl.l"
{ count(); return(VOID); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 56 "idjl.l"
{ count(); return(VOLATILE); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 57 "idjl.l"
{ count(); return(WHILE); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 59 "idjl.l"
{ count(); return(check_type()); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 61 "idjl.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 62 "idjl.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 63 "idjl.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 64 "idjl.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 66 "idjl.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 67 "idjl.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 68 "idjl.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 69 "idjl.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 70 "idjl.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 71 "idjl.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 74 "idjl.l"
{ count(); return(STRING_LITERAL); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 76 "idjl.l"
{ count(); return(ELLIPSIS); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 77 "idjl.l"
{ count(); return(RIGHT_ASSIGN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 78 "idjl.l"
{ count(); return(LEFT_ASSIGN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 79 "idjl.l"
{ count(); return(ADD_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 80 "idjl.l"
{ count(); return(SUB_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 81 "idjl.l"
{ count(); return(MUL_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 82 "idjl.l"
{ count(); return(DIV_ASSIGN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 83 "idjl.l"
{ count(); return(MOD_ASSIGN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 84 "idjl.l"
{ count(); return(AND_ASSIGN); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 85 "idjl.l"
{ count(); return(XOR_ASSIGN); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 86 "idjl.l"
{ count(); return(OR_ASSIGN); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 87 "idjl.l"
{ count(); return(RIGHT_OP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 88 "idjl.l"
{ count(); return(LEFT_OP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 89 "idjl.l"
{ count(); return(INC_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 90 "idjl.l"
{ count(); return(DEC_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 91 "idjl.l"
{ count(); return(PTR_OP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 92 "idjl.l"
{ count(); return(AND_OP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 93 "idjl.l"
{ count(); return(OR_OP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 94 "idjl.l"
{ count(); return(LE_OP); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 95 "idjl.l"
{ count(); return(GE_OP); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 96 "idjl.l"
{ count(); return(EQ_OP); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 97 "idjl.l"
{ count(); return(NE_OP); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 98 "idjl.l"
{ count(); return(';'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 99 "idjl.l"
{ count(); return('{'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 100 "idjl.l"
{ count(); return('}'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 101 "idjl.l"
{ count(); return(','); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 102 "idjl.l"
{ count(); return(':'); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 103 "idjl.l"
{ count(); return('='); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 104 "idjl.l"
{ count(); return('('); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 105 "idjl.l"
{ count(); return(')'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 106 "idjl.l"
{ count(); return('['); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 107 "idjl.l"
{ count(); return(']'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 108 "idjl.l"
{ count(); return('.'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 109 "idjl.l"
{ count(); return('&'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 110 "idjl.l"
{ count(); return('!'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 111 "idjl.l"
{ count(); return('~'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 112 "idjl.l"
{ count(); return('-'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 113 "idjl.l"
{ count(); return('+'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 114 "idjl.l"
{ count(); return('*'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 115 "idjl.l"
{ count(); return('/'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 116 "idjl.l"
{ count(); return('%'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 117 "idjl.l"
{ count(); return('<'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 118 "idjl.l"
{ count(); return('>'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 119 "idjl.l"
{ count(); return('^'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 120 "idjl.l"
{ count(); return('|'); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 121 "idjl.l"
{ count(); return('?'); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 122 "idjl.l"
{ count(); return('@'); } /* alterado */
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 123 "idjl.l"
{ count(); return('#'); } /* alterado */
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 124 "idjl.l"
{ count(); return('$'); } /* alterado */
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 129 "idjl.l"
{ count(); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 130 "idjl.l"
{ /* Add code to complain about unmatched characters */ }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 132 "idjl.l"
ECHO;
	YY_BREAK
#line 1486 "tokens.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 320 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 320 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 319);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 132 "idjl.l"



int yywrap(void)
{
	return 1;
}


void comment(void)
{
	char c, prev = 0;
  
	while ((c = input()) != 0)      /* (EOF maps to 0) */
	{
		if (c == '/' && prev == '*')
			return;
		prev = c;
	}
	error("unterminated comment");
}


int column = 0;

void count(void)
{
	int i;

	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n')
			column = 0;
		else if (yytext[i] == '\t')
			column += 8 - (column % 8);
		else
			column++;

	ECHO;
}


int check_type(void)
{
/*
* pseudo code --- this is what it should check
*
*	if (yytext == type_name)
*		return TYPE_NAME;
*
*	return IDENTIFIER;
*/

/*
*	it actually will only return IDENTIFIER
*/

	return IDENTIFIER;
}
